$Field('TextField')
$Field('TextField','class:invalid error;title: Invalid input')
$Field('TextareaField','required;placeholder:Enter your message here')
$Field('NumericField','required')
$Field('PasswordField')
$Field('EmailField')
$Field('TimeField')
$Field('DateField')
$Field('DropdownField')
$Field('CheckboxField')
$Field('CheckboxSetField')
$Field('OptionsetField')
